FunAppointement/Controllers/AuthentificationController.cs
using FunAppointement.Models;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace WebApplication1.Controllers
{
    public class AuthentificationController : Controller
    {
        // GET: Authentification
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            if (user.Pseudo != null || user.Password != null)
            {
                using (var context = new FunAppointementUsers())
                {
                    if (context.Users.Any(n => n.Pseudo == user.Pseudo && n.Password == user.Password))
                    {
                        FormsAuthentication.SetAuthCookie(user.IDUser.ToString(), true);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.Message = "Identifiant/MDP incorrects";
                        return View("Login");
                    }
                }
            }
            else
            {
                ViewBag.Message = "Veuillez remplir les champs";
                return View("Login");
            }
        }
    }
}

FunAppointement/Views/Authentification/CreateUser.cshtml
@model FunAppointement.Models.User

@{
    ViewBag.Title = "Créer un utilisateur";
}

<h2>Créer un utilisateur</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Utilisateur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pseudo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pseudo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pseudo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDLocation, "IDLocation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDLocation", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Validated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Validated)
                    @Html.ValidationMessageFor(model => model.Validated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FunAppointement/Views/Authentification/Login.cshtml
@model FunAppointement.Models.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Veuillez-vous identifier</h2>

<h3>@ViewBag.Message</h3>

@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <td align="right">Identifiant :</td>
            <td>@Html.EditorFor(n => n.Pseudo)</td>
        </tr>
        <tr></tr>
        <tr>
            <td align="right">Mot de passe :</td>
            <td>@Html.EditorFor(n => n.Password)</td>
        </tr>
    </table>

    <input type="submit" class=" btn-group-lg" value="Se connecter" />
}

<li>@Html.ActionLink("S'enregistrer", "Authentification", "CreateUser")</li>