FunAppointement/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FunAppointement;
using FunAppointement.Models;

namespace FunAppointement.Controllers
{
    public class ActivitiesController : Controller
    {
        private FunAppointementDB db = new FunAppointementDB();

        // GET: Activities
        public async Task<ActionResult> Index()
        {
            var activities = db.Activities.Include(a => a.Group).Include(a => a.TypeActivity);
            return View(await activities.ToListAsync());
        }

        // GET: Activities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await db.Activities.FindAsync(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activities/Create
        public ActionResult Create()
        {
            ViewBag.IDGroup = new SelectList(db.Groups, "IDGroup", "NameGroup");
           
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name");
            return View();
        }

        // POST: Activities/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IDActivity,Plage,Date,Validated,IDTypeActivity,IDGroup")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Activities.Add(activity);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IDGroup = new SelectList(db.Groups, "IDGroup", "NameGroup", activity.IDGroup);
            
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name", activity.IDTypeActivity);
            return View(activity);
        }

        // GET: Activities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await db.Activities.FindAsync(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDGroup = new SelectList(db.Groups, "IDGroup", "NameGroup", activity.IDGroup);
           
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name", activity.IDTypeActivity);
            return View(activity);
        }

        // POST: Activities/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IDActivity,Plage,Date,Validated,IDTypeActivity,IDGroup")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IDGroup = new SelectList(db.Groups, "IDGroup", "NameGroup", activity.IDGroup);
            
            ViewBag.IDTypeActivity = new SelectList(db.TypeActivities, "IDTypeActivity", "Name", activity.IDTypeActivity);
            return View(activity);
        }

        // GET: Activities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await db.Activities.FindAsync(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Activity activity = await db.Activities.FindAsync(id);
            db.Activities.Remove(activity);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FunAppointement/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FunAppointement.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }
    }
}

FunAppointement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FunAppointement</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Retour à l'accueil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Utilisateurs", "Index", "Users")</li>
                    <li>@Html.ActionLink("Activités", "Index", "Activities")</li>
                    <li>@Html.ActionLink("Calendrier", "Index", "Calendar")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel='stylesheet' href='~/Content/fullcalendar.css' />
    @*<link href='~/Content/scheduler.css' rel='stylesheet' />*@
    <script src='~/Scripts/lib/jquery.min.js'></script>
    <script src='~/Scripts/lib/moment.min.js'></script>
    <script src='~/Scripts/fullcalendar.js'></script>
    <script src='~/Scripts/lib/jquery-ui.custom-datepicker.js'></script>
    <script src='~/Scripts/locale-all.js'></script>
    @*<script src='~/Scripts/scheduler.js'></script>*@
</body>
</html>

<script>
    $(function () {
        $('#calendar').fullCalendar({
            schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
            defaultView: 'agendaWeek',
            locale:'fr',
            aspectRatio: 2,
            slotDuration: '04:00:00',
            minTime: '08:00:00',
            maxTime: '24:00:00',
            minHeight: '100',
            windowResize: function (defaultView) {
                alert('The calendar has adjusted to a window resize');
            },

            events: [
                // events go here
            ],
            groupByDateAndResource: true,
            resources: [
            ],

            header: {
                left: 'prev,next today ',
                center: 'addEventButton',
                right: 'month,agendaWeek,agendaDay'
                
            },

            customButtons: {
                addEventButton: {
                    text: 'Ajouter Disponibilité',
                    click: function () {
                        var dateStr = prompt('Entrez une date AAAA-MM-JJ');
                        var slot = prompt('Entrer une plage : 1 - 8h/12h\
                           2 - 12h / 16h\
                            3 - 16h / 20h\
                           4 - aprés 20h');
                            
                        var date = (dateStr);

                            if (date.isValid()) {
                            $('#calendar').fullCalendar('renderEvent', {
                                title: 'Disponible',
                                start: date,
                                allDay: false
                            });
                                alert('Great. Now, update your database...');
                            } else {
                                alert('Invalid date.');
                            }
                    }
                }
            }
        });
    });
</script>